image: cockpithq/cockpit:core-2.5.2
resources:
  requests:
    cpu: "500m"
  limits:
    cpu: "1000m"
hpa:
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
service:
  # on which port to expose?
  port: 8080
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: "cockpit-talon-test"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
mongodb:
  auth:
    enabled: false
  replicaCount: 1
  service:
    nameOverride: "mongodb"
  persistence:
    enabled: false