apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cockpit-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cockpit
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics: {{ toYaml .Values.hpa.metrics | nindent 2 }}