apiVersion: v1
kind: Service
metadata:
  name: cockpit-svc
  annotations: {{ toYaml .Values.service.annotations | nindent 6 }}
spec:
  selector:
    app: cockpit
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80